name: deprem_bildirim
description: Basit deprem bildirim UI taslağı (Flutter)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/AppIcon.png"
  adaptive_icon_background: "#FF3333"
  adaptive_icon_foreground: "assets/AppIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Icons/Refresh.svg
    - assets/Icons/Friends.svg
    - assets/Icons/Chat.svg
    - assets/Icons/Map.svg
    - assets/Icons/History.svg
    - assets/Icons/Settings.svg
    - assets/Icons/Logo.svg
    - assets/Icons/user-stroke-rounded.svg
